print('Divciparu skaitļa ciparu summas aprēķins \n Ievadied divciparu skaitli!')
skola = int(input())
print('divciparu skaitlis =', int(skola))
digit1 = str(skola)
digit2 = str(skola)
print('pirmais cipars:', digit1[0])
print('otrais cipars:', digit2[1])
sum = int(digit1[0]) + int(digit2[1])
print(sum)